### ISSUE TITLE
Only export relevant data

### ISSUE THREAD

**Issue by GTcreyon** [rayyaw/flash-patcher#12]
When trying to patch Super Mario 63 in v2.0.0, the decompilation process takes exceedingly long because of the large number of assets that are being exported. None of these assets are going to be used, because my patch does not include changes to images, sounds, shapes etc. Would it be possible to instead only export the assets as defined in an asset pack?

**Comment by rayyaw** [comment]
Load times will be fixed via caching rather than faster decompilation. Issue labeled as wontfix and closed.
If load times remain too slow after caching is implemented, feel free to reopen this issue.

**Comment by rayyaw** [comment]
Reopening with message: Do we need to export anything other than scripts? We will always import everything when recompiling anyway.

Will look into this for a future release.

**Comment by GTcreyon** [comment]
> Load times will be fixed via caching rather than faster decompilation.

I object to this. Yes, caching would help for repeated compilation, but the entire bank of resources are still exported on the initial run in order to cache them. SM63's initial export process takes over an hour, and while this is manageable, it would be preferable not to have to subject users to this wait when they just want to patch the game once to install a simple mod and be done with it.

If it's any help, the vast majority of the export time is taken on the `sprites` folder. My patch does not alter any of these, it simply needs to add one more. It seems excessive to export a vast array of data that I'm not going to use, especially when the sprite folder alone now takes up over 1GB of storage.

Does FFDec make it possible to export only a specific file, or perhaps only a specific type of file?


[This was discussed in DMs, but I'm posting it here for archival purposes.]

**Comment by GTcreyon** [comment]
> Reopening with message: Do we need to export anything other than scripts? We will always import everything when recompiling anyway.
> 
> Will look into this for a future release.

Yeah, I think only scripts need to be exported. There's no real meaning to the notion of "patching" any of the other asset files, only replacing them outright, so only scripts need an export.
