### ISSUE TITLE
Assets cannot be added if they do not already exist

### ISSUE THREAD

**Issue by GTcreyon** [rayyaw/flash-patcher#21]
Currently, asset packs can only overwrite existing files, not create new ones. It would be useful if they had the ability to create files too.

**Comment by rayyaw** [comment]
This seems to be a limitation within JPEXS. Even by trying to import images through the GUI, I have been unable to do so. Can you provide a video showing how to import an additional image into a SWF?

Will resolve this issue in 7 days if no additional comments are added by then.

**Comment by rayyaw** [comment]
On further inspection, Flash Patcher seems to be injecting the image into `./.Patcher-Temp` correctly, which means it should be recompiling. The JPEXS recompiler is likely at fault here.

**Comment by rayyaw** [comment]
No further details have been posted, resolving
