### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by GTcreyon** [rayyaw/flash-patcher#26]
It would be nice if the script were unit-testable. If additional functionality is to be added, then the code will need to be confirmed as robust (or at least, the developer should be aware if any breaking changes occur).

This would likely consist of a sample SWF file, and a set of sample patches that test various features.

**Comment by rayyaw** [comment]
Some minor refactor is still required, will begin work on this in the next few days.

**Comment by rayyaw** [comment]
We should add the following checks to run on any pull request or push (using GitHub Actions):
- pylint
- unit tests
- enforce line and branch coverage > 90%

**Comment by rayyaw** [comment]
We should also add integration tests by running flash-patcher and then diff'ing the SWFs.

**Comment by rayyaw** [comment]
We are also migrating from `sys.exit()` to proper exceptions `raise Exception` as we migrate towards becoming a pip-compatible package.

**Comment by rayyaw** [comment]
Looks like someone's already done something similar: https://github.com/marketplace/actions/python-coverage
Will include this in my next PR, which will be the final one for this issue.
