### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by Aethusx** [rayyaw/flash-patcher#3]
With simple workaround this script works on windows.

`short_name = ' '.join(split_line[1:-1]).replace('/', '\\')`

What about creating proper support for windows

**Comment by rayyaw** [comment]
I plan to work on full Windows support for release 1.5. I need to find how Windows stores JPEXS (and how to run JPEXS in windows) before starting this.

I'll auto-detect your version of JPEXS and then use that to run, it shouldn't be too difficult to add.

If you use WSL it'll work through WSL though.

**Comment by rayyaw** [comment]
I've added automatic version detection but it's not working for Windows yet. Do you know what the full path of the JPEXS executable is in Windows?

**Comment by rayyaw** [comment]
Windows is now supported, let me know if there are any errors when running
