### ISSUE TITLE
Switching line numbers in add blocks

### ISSUE THREAD

**Issue by GTcreyon** [rayyaw/flash-patcher#8]
To simplify patch files, it would be useful to allow the user to skip to a certain line during an `add` block.

For example, instead of writing:
```
add frame_1/DoAction.as 100
trace("a")
end-patch

add frame_1/DoAction.as 200
trace("b")
end-patch
```
It would be desirable to instead write it as something like:
```
add frame_1/DoAction.as 100
trace("a")
>>200
trace("b")
end-patch
```
Where the `>>200` line skips ahead to line 200.

**Comment by GTcreyon** [comment]
Nevermind, this is fixed in v2.0.0

**Comment by rayyaw** [comment]
Preliminary syntax will likely look something like this:

```
// cmd: skip 10
```

10 is the number of lines to skip. Include the slashes at the beginning of the line (this is so it acts like a comment in ActionScript)

**Comment by rayyaw** [comment]
v3.0.0 has been designed around this, this change will be relatively easy to implement with the v3 syntax
