### ISSUE TITLE
Negative content offsets

### ISSUE THREAD

**Issue by GTcreyon** [rayyaw/flash-patcher#86]
The parser should allow for negative offsets from content, to move backwards in the file before injecting.

For example,
```
add file.as
begin-content
foo()
end-content - 5
```

**Comment by rayyaw** [comment]
this should be pretty simple, as it only requires some changes to the grammar files. I'll see what I can do this weekend

**Comment by rayyaw** [comment]
Due to significant parsing issues, this will be marked as wontfix. Parsing negative numbers differently from intervals of 2 numbers would likely require a breaking syntax change.

If you want to contribute this, pull requests are welcome.
