### ISSUE TITLE
Modify the SWF file contained in the binary data contained in the SWF file

### ISSUE THREAD

**Issue by liuyutian813** [rayyaw/flash-patcher#88]
If there is binary data in a SWF file and it contains another SWF file, how do I modify its AS3 script?

**Comment by rayyaw** [comment]
You should manually decompile the top level SWF, and get the inner SWF. You can then apply Flash Patcher to the inner SWF.
You can use the FFDec CLI to automate this: `ffdec --help`.

Flash Patcher doesn't currently support modifying inner SWFs but you should be able to use some automation as mentioned above as a workaround. We currently do not have plans to support this feature.
